#!/usr/bin/env bash
# Inspects any core dumps found in COREDUMP_DIR, resolves their executables,
# and prints stacktraces and register states via GDB. Exits 1 if any dumps exist.
set -euo pipefail

COREDUMP_DIR="${COREDUMP_DIR:-/tmp/coredumps}"

shopt -s nullglob
cores=("${COREDUMP_DIR}"/core*)
if [ ${#cores[@]} -eq 0 ]; then
  echo "No crashdumps found in ${COREDUMP_DIR}."
  exit 0
fi

echo "Found ${#cores[@]} crashdump(s) in ${COREDUMP_DIR}:"
ls -lh "${cores[@]}"

# Ensure gdb is installed on the runner
if ! command -v gdb >/dev/null 2>&1; then
  echo "gdb not found, installing..."
  sudo apt-get update -qq && sudo apt-get install -y -qq --no-install-recommends gdb
fi

for core in "${cores[@]}"; do
  echo ""
  echo "======================================================================"
  echo "CRASHDUMP: ${core}"
  echo "======================================================================"

  if command -v file >/dev/null 2>&1; then
    file "${core}" || true
  fi

  # Resolve the executable that generated the core dump:
  # 1. Try reading the command from GDB's core header ("Core was generated by `...'")
  EXE=""
  CMD_INFO=$(gdb --batch --core="${core}" 2>&1 || true)
  EXE_CANDIDATE=$(echo "${CMD_INFO}" | awk -F"[\` ']" '/Core was generated by/ {print $5}' || true)
  if [ -z "${EXE_CANDIDATE}" ] && command -v file >/dev/null 2>&1; then
    FILE_INFO=$(file "${core}" 2>/dev/null || true)
    EXE_CANDIDATE=$(echo "${FILE_INFO}" | awk -F"'" '{print $2}' | awk '{print $1}' || true)
  fi
  if [ -n "${EXE_CANDIDATE}" ] && [ -f "${EXE_CANDIDATE}" ]; then
    EXE="${EXE_CANDIDATE}"
  fi

  # 2. If not an absolute file path, check PATH or current working directory
  if [ -z "${EXE}" ] && [ -n "${EXE_CANDIDATE}" ]; then
    if command -v "${EXE_CANDIDATE}" >/dev/null 2>&1; then
      EXE=$(command -v "${EXE_CANDIDATE}")
    elif [ -f "./${EXE_CANDIDATE}" ]; then
      EXE="./${EXE_CANDIDATE}"
    fi
  fi

  # 3. If candidate is a Postgres process, fall back to known installation paths
  if [ -z "${EXE}" ] || [[ "${EXE_CANDIDATE}" == *"postgres"* ]]; then
    if [ -n "${PG_VERSION:-}" ] && [ -f "/usr/lib/postgresql/${PG_VERSION}/bin/postgres" ]; then
      EXE="/usr/lib/postgresql/${PG_VERSION}/bin/postgres"
    elif command -v postgres >/dev/null 2>&1; then
      EXE=$(command -v postgres)
    else
      FIND_PG=$(find /home/runner/.pgrx /usr/lib/postgresql -name postgres -type f 2>/dev/null | head -n 1 || true)
      if [ -n "${FIND_PG}" ] && [ -f "${FIND_PG}" ]; then
        EXE="${FIND_PG}"
      fi
    fi
  fi

  echo "Resolved executable: ${EXE:-<unknown>}"
  echo "--- Backtrace ---"

  # Print registers, crashing thread backtrace (with locals), and all thread backtraces
  if [ -n "${EXE}" ] && [ -f "${EXE}" ]; then
    gdb --batch \
      -ex "set pagination off" \
      -ex "set print elements 100" \
      -ex "info registers" \
      -ex "bt full" \
      -ex "thread apply all bt full" \
      "${EXE}" "${core}" || true
  else
    gdb --batch \
      -ex "set pagination off" \
      -ex "set print elements 100" \
      -ex "info registers" \
      -ex "bt full" \
      -ex "thread apply all bt full" \
      --core="${core}" || true
  fi
  echo "======================================================================"
done

# Exit with non-zero status so the job records a failure when crashes occur
exit 1
