coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
        informational: true
    patch:
      default:
        target: 80%
        threshold: 5%
        informational: true

comment:
  layout: "reach, diff, flags, files"
  behavior: default

ignore:
  - "node_modules/**/*"
  - "docs/**/*"
  - "benchmarks/**/*"
  - "**/*_test.rs"
  - "**/tests/**"
