name: "Commit and Push File"

description: Checks out the specified remote repository, stages the provided file, commits it if there are changes, and pushes to the given branch.

inputs:
  repository:
    description: "Remote repository in owner/name format."
    required: true
  token:
    description: "GitHub token for authentication."
    required: true
  branch:
    description: "Branch to check out and push to."
    required: false
    default: "main"
  repo-path:
    description: "Local path to check out the repo into."
    required: false
    default: "push-file-temp"
  file-name:
    description: "File path (relative to repo) to add and commit."
    required: true
  commit-message:
    description: "Commit message to use."
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout target repository
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        token: ${{ inputs.token }}
        ref: ${{ inputs.branch }}
        path: ${{ inputs.repo-path }}

    - name: Configure Git user
      working-directory: "${{ inputs.repo-path }}"
      run: |
        git config user.name "ParadeDB push file action"
        git config user.email "developers@paradedb.com"

    - name: Stage changes
      working-directory: "${{ inputs.repo-path }}"
      run: |
        cp ../${{ inputs.file-name }} ./
        git add "${{ inputs.file-name }}"

    - name: Commit changes if needed
      id: commit
      working-directory: "${{ inputs.repo-path }}"
      run: |
        if git diff --cached --quiet; then
          echo "no_changes=true" >> $GITHUB_OUTPUT
        else
          git commit -m "${{ inputs.commit-message }}"
          echo "no_changes=false" >> $GITHUB_OUTPUT
        fi

    - name: Push changes
      if: steps.commit.outputs.no_changes == 'false'
      working-directory: "${{ inputs.repo-path }}"
      run: |
        git push origin HEAD:${{ inputs.branch }}

    - name: Cleanup
      run: rm -rf "${{ inputs.repo-path }}"
