title: "[Announcements] "
labels: ["General Introduction"]
body:
  - type: markdown
    attributes:
      value: |
        This discussion type is reserved for maintainers to make announcements about ParadeDB.
