title: "[General] "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: >
        This discussion type is for anything that doesn't fit in another category. If you are looking to raise an issue,
        please do so on the relevant ParadeDB repository:

          * [paradedb/paradedb](https://github.com/paradedb/paradedb/issues/news/) - ParadeDB core and pg_search extension repository
          * [paradedb/charts](https://github.com/paradedb/charts/issues/new/) - ParadeDB Helm Chart repository

        Please report security vulnerabilities using GitHub's [report vulnerability form](https://github.com/paradedb/paradedb/security/advisories/new).

  - type: textarea
    attributes:
      label: What would you like to discuss?
      description: Share a project, ask a question, or start a conversation.
    validations:
      required: true

  - type: markdown
    attributes:
      value: "### Identity Disclosure"
  - type: input
    attributes:
      label: "Full Name:"
      placeholder: e.g., John Doe
    validations:
      required: true
  - type: input
    attributes:
      label: "Affiliation:"
      placeholder: e.g., Acme Corporation
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        If the above is not given and is not obvious from your GitHub profile page, we might close your issue without further review. Please refer to the [reasoning behind this rule](https://berthub.eu/articles/posts/anonymous-help/) if you have questions.
