# This manifest is exclusively intended for usage within the Antithesis platform, as
# it hardcodes the Antithesis registry for the image source.
apiVersion: v1
kind: Pod
metadata:
  name: proptests-runner
  labels:
    app: proptests-runner
spec:
  restartPolicy: Never
  containers:
    - name: proptests
      image: us-central1-docker.pkg.dev/molten-verve-216720/paradedb-repository/proptests
      imagePullPolicy: IfNotPresent
      command:
        - sleep
        - infinity
