blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/paradedb/paradedb/discussions
    about: Please ask and answer general questions here.
  - name: ParadeDB Community Slack
    url: https://join.slack.com/t/paradedbcommunity/shared_invite/zt-32abtyjg4-yoYoi~RPh9MSW8tDbl0BQw
    about: Our Slack community is the best place to get quick help and feedback.
