DROP TABLE IF EXISTS documents CASCADE;
DROP TABLE IF EXISTS files CASCADE;
DROP TABLE IF EXISTS pages CASCADE;
DROP TABLE IF EXISTS docs_schema_metadata CASCADE;
DROP FUNCTION IF EXISTS uuid_text(INTEGER);
