###############################################
# First Stage: Base
###############################################

FROM ubuntu:22.04 as base

# Declare all the build arguments and set them to
# environment variables for use in build and runtime
ARG USE_SCCACHE
ARG PG_VERSION_MAJOR
ARG PG_BM25_VERSION
ARG PGML_VERSION
ARG PGVECTOR_VERSION
ENV USE_SCCACHE=${USE_SCCACHE}
ENV PG_VERSION_MAJOR=${PG_VERSION_MAJOR}
ENV PG_BM25_VERSION=${PG_BM25_VERSION}
ENV PGML_VERSION=${PGML_VERSION}
ENV PGVECTOR_VERSION=${PGVECTOR_VERSION}

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=UTC

# Install common dependencies to builder and runtime
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    wget \
    sudo \
    gnupg \
    gcc \
    software-properties-common \
    ca-certificates \
    python3.10 \
    python3-pip \
    libpython3.10-dev \
    python3.10-dev \
    libopenblas-dev \
    && rm -rf /var/lib/apt/lists/*

# Install apt-fast
RUN /bin/bash -c "$(curl -sL https://git.io/vokNn)"

# Add PostgreSQL's third party repository to get the latest versions
RUN curl -s https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" | tee /etc/apt/sources.list.d/pgdg.list

RUN apt-get update && apt-fast install -y --no-install-recommends \
    postgresql-${PG_VERSION_MAJOR} \
    postgresql-server-dev-${PG_VERSION_MAJOR} \
    && rm -rf /var/lib/apt/lists/*

###############################################
# Second Stage: Builder
###############################################

FROM base as builder

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Install build dependencies
RUN apt-get update && apt-fast install -y --no-install-recommends \
    build-essential \
    checkinstall \
    clang \
    git \
    cmake \
    pkg-config \
    ccache \
    libcurl4-openssl-dev \
    && rm -rf /var/lib/apt/lists/*

# Install Rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:$PATH"

# Set up environment for sccache (Rust) and ccache (C/C++), to speed up builds
# We use both since some extensions are written in Rust and some in C/C++
RUN if [ "${USE_SCCACHE}" = "True" ]; then \
        cargo install sccache && \
        echo "ENV RUSTC_WRAPPER=sccache" >> /root/.bashrc; \
        echo "ENV PATH="/usr/lib/ccache:$PATH"" >> /root/.bashrc; \
    fi

ENV PGX_HOME=/usr/lib/postgresql/${PG_VERSION_MAJOR}

RUN cargo install cargo-pgrx --version 0.9.8

######################
# pg_bm25
######################

FROM builder as builder-pg_bm25

WORKDIR /tmp/pg_bm25

COPY pg_bm25/ /tmp/pg_bm25

# Use the build argument to update the version in Cargo.toml
RUN sed -i "s/version = \"[0-9]*\.[0-9]*\.[0-9]*\"/version = \"${PG_BM25_VERSION}\"/" Cargo.toml

RUN cargo pgrx init "--pg${PG_VERSION_MAJOR}=/usr/lib/postgresql/${PG_VERSION_MAJOR}/bin/pg_config" && \
    cargo pgrx package --pg-config "/usr/lib/postgresql/${PG_VERSION_MAJOR}/bin/pg_config"

######################
# Other extensions
######################

FROM builder as builder-generic

COPY scripts/install_pg_extensions.sh /usr/local/bin/

# Compile and install extensions from source
RUN /usr/local/bin/install_pg_extensions.sh \
    "pgvector,${PGVECTOR_VERSION},https://github.com/pgvector/pgvector/archive/refs/tags/v${PGVECTOR_VERSION}.tar.gz"

####################
# pgml
####################

FROM builder as builder-pgml

RUN apt-get update && apt-fast install -y --no-install-recommends \
    libssl-dev \
    bison \
    flex \
    libreadline-dev \
    libz-dev \
    tzdata \
    libpq-dev \
    libclang-dev \
    && rm -rf /var/lib/apt/lists/*

RUN git clone --branch "v${PGML_VERSION}" "https://github.com/postgresml/postgresml" /tmp/postgresml

WORKDIR /tmp/postgresml/pgml-extension

RUN git submodule update --init --recursive && \
    git fetch --tags && \
    git fetch --depth 1 origin tag "v${PGML_VERSION}" && \
    git checkout "v${PGML_VERSION}"

# Update pgml schema to paradedb
RUN sed -i "s/\(schema = \).*/\1'paradedb'/" pgml.control && \
    find . -type f -exec sed -i 's/pgml\./paradedb\./g' {} +

RUN cargo pgrx init "--pg${PG_VERSION_MAJOR}=/usr/lib/postgresql/${PG_VERSION_MAJOR}/bin/pg_config" && \
    cargo pgrx package --pg-config "/usr/lib/postgresql/${PG_VERSION_MAJOR}/bin/pg_config"

###############################################
# Third Stage: PostgreSQL
###############################################

FROM base as paradedb

WORKDIR /usr/src/app

# Install pgml runtime dependencies
COPY --from=builder-pgml /tmp/postgresml/pgml-extension/requirements.txt /usr/src/app/
RUN pip3 install --no-cache-dir -r requirements.txt && rm -rf requirements.txt

# Copy the pg_bm25 & pgml extensions from their builder stages
COPY --from=builder-pg_bm25 /tmp/pg_bm25/target/release/pg_bm25-pg${PG_VERSION_MAJOR}/usr/share/postgresql/${PG_VERSION_MAJOR}/extension/* /usr/share/postgresql/${PG_VERSION_MAJOR}/extension/
COPY --from=builder-pg_bm25 /tmp/pg_bm25/target/release/pg_bm25-pg${PG_VERSION_MAJOR}/usr/lib/postgresql/${PG_VERSION_MAJOR}/lib/* /usr/lib/postgresql/${PG_VERSION_MAJOR}/lib/
COPY --from=builder-pgml /tmp/postgresml/pgml-extension/target/release/pgml-pg${PG_VERSION_MAJOR}/usr/share/postgresql/${PG_VERSION_MAJOR}/extension/* /usr/share/postgresql/${PG_VERSION_MAJOR}/extension/
COPY --from=builder-pgml /tmp/postgresml/pgml-extension/target/release/pgml-pg${PG_VERSION_MAJOR}/usr/lib/postgresql/${PG_VERSION_MAJOR}/lib/* /usr/lib/postgresql/${PG_VERSION_MAJOR}/lib/

# Copy all other extensions from the builder stage & install them
COPY --from=builder-generic /tmp/*.deb /tmp/
RUN apt-get update && apt-fast install -y --no-install-recommends \
    /tmp/*.deb \
    && rm -rf /var/lib/apt/lists/* /tmp/*

# Copy the database initialization scripts into the container
COPY ./conf/postgresql.conf /etc/postgresql/${PG_VERSION_MAJOR}/main/postgresql.conf
COPY ./conf/pg_hba.conf /etc/postgresql/${PG_VERSION_MAJOR}/main/pg_hba.conf
COPY ./conf/pg_ident.conf /etc/postgresql/${PG_VERSION_MAJOR}/main/pg_ident.conf

# Copy the entrypoint script into the container
COPY ./scripts/entrypoint.sh /usr/src/app

# Create the postgres user and change to it
USER postgres

# Expose the PostgreSQL
EXPOSE 5432

ENTRYPOINT ["/usr/src/app/entrypoint.sh"]
