# Note: Debian Trixie = Debian 13
FROM postgres:15-trixie

# Install pg_search from GitHub Releases
RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends ca-certificates curl; \
    arch="$(dpkg --print-architecture)"; \
    case "$arch" in \
        amd64) checksum="4059be91b771368be1764db22007d8a0c92346e1b1b25830192fa139a992a4a8" ;; \
        arm64) checksum="a5ed45f10973d1505c4b76a320856f5371c471d00780bfc8d63abb4a7a7081ed" ;; \
        *) echo "unsupported architecture: $arch" >&2; exit 1 ;; \
    esac; \
    curl -fsSL -o /tmp/pg_search.deb "https://github.com/paradedb/paradedb/releases/download/v0.25.2/postgresql-15-pg-search_0.25.2-1PARADEDB-trixie_${arch}.deb"; \
    echo "${checksum} */tmp/pg_search.deb" | sha256sum --strict --check -; \
    apt-get install -y --no-install-recommends /tmp/pg_search.deb; \
    apt-get purge -y --auto-remove curl; \
    rm /tmp/pg_search.deb; \
    apt-get dist-clean

# Install pgvector
RUN set -eux; \
    echo "deb [ signed-by=/usr/local/share/keyrings/postgres.gpg.asc ] https://apt-archive.postgresql.org/pub/repos/apt trixie-pgdg-archive main" > /etc/apt/sources.list.d/pgdg-archive.list; \
    apt-get update; \
    apt-get install -y --no-install-recommends postgresql-15-pgvector=0.8.5-1.pgdg13+1; \
    apt-get dist-clean

RUN set -eux; \
    echo "shared_preload_libraries = 'pg_search'" >> /usr/share/postgresql/postgresql.conf.sample

COPY ./bootstrap_official.sh /docker-entrypoint-initdb.d/10_bootstrap_paradedb.sh

# The upstream `postgres` Docker image comes with its own `entrypoint.sh` script which
# starts as `root` and then switches to the `postgres` user after running chown and chmod
# on the PostgreSQL data directory. To maintain compatibility with the upstream image and
# ensure that the `postgres` user has the correct permissions on the data directory, we let
# the upstream `entrypoint.sh` script run as the entrypoint and don't specify a custom user.
