FROM scratch

ARG PG_VERSION_MAJOR
ARG COMMIT_SHA

# Declare buildtime environment variables
ENV PG_VERSION_MAJOR=${PG_VERSION_MAJOR} \
    COMMIT_SHA=${COMMIT_SHA}

COPY docker/docker-compose.antithesis.yml /docker-compose.yaml
