name: Install pg_search from source
description: Compile, install, and start pg_search for a benchmark cluster

inputs:
  pg_version:
    description: "PostgreSQL major version to build against."
    required: false
    default: "18"

runs:
  using: composite
  steps:
    - name: Compile and install pg_search
      shell: bash
      run: >-
        cargo pgrx install -p pg_search --sudo --release
        --pg-config "/usr/lib/postgresql/${{ inputs.pg_version }}/bin/pg_config"
        --features=pg${{ inputs.pg_version }} --no-default-features

    - name: Start PostgreSQL
      shell: bash
      working-directory: pg_search/
      run: cargo pgrx start pg${{ inputs.pg_version }}
