GRANT USAGE, CREATE ON SCHEMA pdb TO PUBLIC;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA pdb TO PUBLIC;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA pdb TO PUBLIC;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA pdb TO PUBLIC;

ALTER DEFAULT PRIVILEGES IN SCHEMA pdb GRANT ALL PRIVILEGES ON TABLES TO PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA pdb GRANT ALL PRIVILEGES ON SEQUENCES TO PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA pdb GRANT ALL PRIVILEGES ON FUNCTIONS TO PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA pdb GRANT USAGE ON TYPES TO PUBLIC;
