workload = "workloads/replicated-events.toml"

[routes.read]
destinations = ["SubscriberA", "SubscriberB"]
refresh_scale = 2.0

[routes.write]
destinations = ["Publisher"]

[[server]]
name = "Publisher"
setup_template = "writer"
[server.style.Automatic]
postgresql_conf = "Publisher"

[server.setup]
sql = "CREATE PUBLICATION stressgres_pub FOR TABLE events;"
[server.teardown]
sql = ""
[server.monitor]
refresh_ms = 100
title = "Subscriber Lag"
log_columns = ["subscriber_count"]
sql = "SELECT count(*) AS subscriber_count FROM pg_stat_replication;"

[[server]]
name = "SubscriberA"
setup_template = "reader"
[server.style.Automatic]
postgresql_conf = "Subscriber"

[server.setup]
sql = """
CREATE SUBSCRIPTION stressgres_sub_a CONNECTION '@Publisher_CONNSTR@' PUBLICATION stressgres_pub;
SELECT pg_sleep(5);
"""
[server.teardown]
sql = ""
[server.monitor]
refresh_ms = 100
title = "Subscriber A Documents"
log_columns = ["document_count"]
sql = "SELECT count(*) AS document_count FROM events;"

[[server]]
name = "SubscriberB"
setup_template = "reader"
[server.style.Automatic]
postgresql_conf = "Subscriber"

[server.setup]
sql = """
CREATE SUBSCRIPTION stressgres_sub_b CONNECTION '@Publisher_CONNSTR@' PUBLICATION stressgres_pub;
SELECT pg_sleep(5);
"""
[server.teardown]
sql = ""
[server.monitor]
refresh_ms = 100
title = "Subscriber B Documents"
log_columns = ["document_count"]
sql = "SELECT count(*) AS document_count FROM events;"
