root_table = "stackoverflow_posts"
sampling_seed = 8097114971001016866 #"ParadeDB" in ascii

[[tables]]
name = "stackoverflow_posts"

[[tables]]
name = "comments"
parent = "stackoverflow_posts"
parent_join_col = "id"
join_col = "post_id"

[[tables]]
name = "users"
parent = "stackoverflow_posts"
parent_join_col = "owner_user_id"
join_col = "id"
