root_table = "stackoverflow_posts"
sampling_seed = 5792036358396920898 #"ParadeDB" ascii values, converted to hex, then concatenated

[[tables]]
name = "stackoverflow_posts"

[[tables]]
name = "comments"
parent = "stackoverflow_posts"
parent_join_col = "id"
join_col = "post_id"

[[tables]]
name = "users"
parent = "stackoverflow_posts"
parent_join_col = "owner_user_id"
join_col = "id"
