name: Set Up Benchmarker
description: Checkout the benchmarker repository, set up Go, and build binaries

inputs:
  repository:
    description: "Repository to clone"
    required: false
    default: "paradedb/benchmarker"
  ref:
    description: "Ref to checkout"
    required: false
    default: "main"
runs:
  using: composite
  steps:
    - name: Checkout benchmarker (${{ inputs.ref }})
      uses: actions/checkout@v7
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        path: benchmarker

    - name: Set Up Go
      uses: actions/setup-go@v7
      with:
        go-version-file: benchmarker/go.mod
        cache-dependency-path: benchmarker/go.sum

    - name: Build benchmarker (k6 + loader)
      shell: bash
      working-directory: benchmarker
      env:
        GOTOOLCHAIN: auto
      run: make
