root_table = "orders"
sampling_seed = 5792036358396920898 #"ParadeDB" in ascii

[[tables]]
name = "orders"

[[tables]]
name = "lineitem"
parent = "orders"
parent_join_col = "o_orderkey"
join_col = "l_orderkey"

[[tables]]
name = "partsupp"
parent = "lineitem"
parent_join_col = "l_partkey"
join_col = "ps_partkey"
