root_table = "orders"
sampling_seed = 579203635839692 #"Parade" ascii values, converted to hex, then concatenated

[[tables]]
name = "orders"

[[tables]]
name = "lineitem"
parent = "orders"
parent_join_col = "o_orderkey"
join_col = "l_orderkey"

[[tables]]
name = "partsupp"
parent = "lineitem"
parent_join_col = "l_partkey"
join_col = "ps_partkey"
