name: Cherry Pick

on:
  pull_request_target: # pull_request_target enables cherry-picks from forked repos
    branches:
      - main
    types: [closed]

permissions:
  contents: write
  pull-requests: write

jobs:
  backport:
    name: Backport (Cherry Pick)
    if: >
      github.event.pull_request.merged == true &&
      contains(join(github.event.pull_request.labels.*.name, ','), 'cherry-pick/')
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.PARADEDB_GITHUB_APP_CLIENT_ID }}
          private-key: ${{ secrets.PARADEDB_GITHUB_APP_PRIVATE_KEY }}

      - name: Checkout Git Repository
        uses: actions/checkout@v7
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.event.pull_request.base.ref }}
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Backport based on cherry-pick/<branch> labels
        uses: korthout/backport-action@v4
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          git_committer_name: paradedb-github-app[bot]
          git_committer_email: 282009505+paradedb-github-app[bot]@users.noreply.github.com
          add_author_as_assignee: true
          add_author_as_reviewer: true
          add_labels: automated-cherry-pick
          pull_title: "${pull_title}"
          label_pattern: "^cherry-pick/([^ ]+)$"
          experimental: |
            {
              "conflict_resolution": "draft_commit_conflicts"
            }
