name: Dispatch Sync to New Enterprise Repository (Enterprise As Branch) on Main Merge

on:
  push:
    branches:
      - main

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger sync in Enterprise Patch Repository
        run: |
          curl --fail -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PARADEDB_BOT_GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Content-Type: application/json" \
            https://api.github.com/repos/paradedb/enterprise-as-branch/dispatches \
            -d '{
              "event_type": "run-community-rebase",
              "client_payload": {
                "sha": "${{ github.sha }}",
                "repo": "${{ github.repository }}",
                "ref": "${{ github.ref }}"
              }
            }'
