# workflows/lint-format.yml
#
# Lint Format
# Lint the project's file trailing spaces, line endings, and format.

name: Lint Format

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

concurrency:
  group: lint-format-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint-format:
    name: Lint File Endings & Trailing Whitespaces
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v7

      - name: Lint Format
        uses: paradedb/actions/lint-format@b7703a0b117808acb8a659ca94be8ba274344289
        with:
          exclude: |
            *.nix
            *.sql
            *.out
            *.rs
            docker/manifests/**
          check-json: "true"
