# workflows/lint-markdown.yml
#
# Lint Markdown
# Lint Markdown files using markdownlint and Prettier.

name: Lint Markdown

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - ".github/workflows/lint-markdown.yml"
      - "**/*.md"
      - "**/*.mdx"
  workflow_dispatch:

concurrency:
  group: lint-markdown-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint-markdown:
    name: Lint Markdown Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v7

      - name: Lint Markdown
        uses: paradedb/actions/lint-prettier@v12
        with:
          patterns: "{**/*.md,**/*.mdx}"
          markdown: "true"
          ignore-path: .prettierignore
