# workflows/lint-bash.yml
#
# Lint Bash
# Lint and enforce good practices for Bash scripts.

name: Lint Bash

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - ".github/workflows/lint-bash.yml"
      - "**/*.sh"
  workflow_dispatch:

concurrency:
  group: lint-bash-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint-bash:
    name: Lint Bash Scripts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v7

      - name: Lint Bash
        uses: paradedb/actions/lint-bash@v12
        with:
          allow-sh: "true"
          strict-mode-exclude: docker/bootstrap_official.sh
