# workflows/lint-docker.yml
#
# Lint Docker
# Lint Dockerfiles using Hadolint.

name: Lint Docker

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - ".github/workflows/lint-docker.yml"
      - "docker/**"
  workflow_dispatch:

concurrency:
  group: lint-docker-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint-docker:
    name: Lint Dockerfiles
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v6

      - name: Verify Generated Dockerfiles Are In Sync With Template
        run: |
          docker/generate-dockerfiles.sh
          git diff --exit-code -- docker

      - name: Run Hadolint
        uses: jbergstroem/hadolint-gh-action@v1
        with:
          dockerfile: "docker/**/Dockerfile docker/Dockerfile.config docker/Dockerfile.stressgres"
          error_level: 2 # Treat INFO as error
