# workflows/publish-pg_search-pgxn.yml
#
# Publish pg_search (PGXN)
# Bundle and publish the pg_search extension source to the PostgreSQL Extension Network (PGXN).
# This workflow runs `make dist` on the selected branch or tag and uses the version in Cargo.toml.
# It is triggered on creation of a v* GitHub Tag or run manually, but beta (-rc.) releases get
# filtered out by the `if` condition of the job. Select the release tag when running it manually.

name: Publish pg_search (PGXN)

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish-pg_search-pgxn:
    name: Publish pg_search to PGXN
    runs-on: ubuntu-latest
    if: ${{ !contains(github.ref, '-rc.') }}
    container: pgxn/pgxn-tools

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v7

      - name: Bundle the Release
        run: make dist

      - name: Release on PGXN
        env:
          PGXN_USERNAME: ${{ secrets.PGXN_USERNAME }}
          PGXN_PASSWORD: ${{ secrets.PGXN_PASSWORD }}
        run: pgxn-release

      - name: Notify Slack on Failure
        if: failure()
        uses: paradedb/actions/slack-alert@v14
        with:
          webhook_url: ${{ secrets.SLACK_GITHUB_CHANNEL_WEBHOOK_URL }}
          mention: "<!subteam^S0BLE20RYPM|@pg_search-maintainers>"
          title: "${{ github.workflow }} Failed"
