# workflows/publish-pg_search-pgxn.yml
#
# Publish pg_search (PGXN)
# Build and publish the pg_search extension to the PostgreSQL Extension Network (PGXN). This
# workflow is triggered on creation of a GitHub Tag, but beta releases get filtered out
# by the `if` condition of the job.

name: Publish pg_search (PGXN)

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  publish-pg_search-pgxn:
    name: Publish pg_search to PGXN
    runs-on: ubuntu-latest
    # Only ParadeDB Community is shipped to PGXN
    if: ${{ !contains(github.ref, '-rc.') && github.repository == 'paradedb/paradedb' }}
    container: pgxn/pgxn-tools

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v7

      - name: Bundle the Release
        run: make dist

      - name: Release on PGXN
        env:
          PGXN_USERNAME: ${{ secrets.PGXN_USERNAME }}
          PGXN_PASSWORD: ${{ secrets.PGXN_PASSWORD }}
        run: pgxn-release

      - name: Notify Slack on Failure
        if: failure()
        run: |
          GITHUB_RUN_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          MESSAGE="<!here> \`publish-pg_search-pgxn\` workflow failed in \`${{ github.repository }}\` on branch \`${{ github.ref_name }}\` -- investigate immediately! GitHub Action Logs: ${GITHUB_RUN_URL}"
          curl -X POST -H 'Content-type: application/json' -d "{\"text\": \"${MESSAGE}\"}" ${{ secrets.SLACK_GITHUB_CHANNEL_WEBHOOK_URL }}
